# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bd6558ccad579184ed2c6d618278f46497096734fa45113f9c64b506e95db6bb614715a436003a82fe1f1de9b54eb1869239938370d9c13d464a803515095d8

test:
  secret_key_base: c495fe9df4b30eadf538dff494910b6d6982223b6b5bec748a4c87f6d0053205091e840a5f069226dc47c4271d8ec9e88b88ffc69721c429d9f4ab009143ed4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
